"""clean

Revision ID: a4af03b3a7b5
Revises: 
Create Date: 2023-01-31 17:13:25.852064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4af03b3a7b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('street_1', sa.String(), nullable=False),
    sa.Column('street_2', sa.String(), nullable=True),
    sa.Column('street_3', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=False),
    sa.Column('city', sa.String(), server_default=sa.text("'Example_city'"), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_identifier', sa.String(), nullable=False),
    sa.Column('name', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('initials', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname_prefix', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('phone', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mobile', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('email', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tr_file_status', sa.String(), server_default='pending', nullable=True),
    sa.Column('display_number', sa.String(), nullable=True),
    sa.Column('invoice_reference', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('equipment_type', sa.String(), nullable=True),
    sa.Column('modality', sa.String(), nullable=True),
    sa.Column('service_level', sa.String(), nullable=True),
    sa.Column('customs', sa.String(), nullable=True),
    sa.Column('attention_required', sa.Boolean(), nullable=True),
    sa.Column('multi_trip', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('multi_activity', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('date_deviation', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('urgency', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('late_booking', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('cost_code', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('reported', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('call_before_planning', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('incoterms', sa.String(), nullable=True),
    sa.Column('certainty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reference', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_reference', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('transport_file_id', sa.Integer(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('time_prefix', sa.String(), nullable=True),
    sa.Column('time_1', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('time_2', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('instructions', sa.String(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['transport_file_id'], ['transport_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('loading_meters', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('net_weight', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('gross_weight', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('dangerous_goods', sa.Boolean(), nullable=False),
    sa.Column('dg_class', sa.String(), nullable=True),
    sa.Column('dg_product_group', sa.String(), nullable=True),
    sa.Column('dg_un_code', sa.String(), nullable=True),
    sa.Column('dg_technical_name', sa.String(), nullable=True),
    sa.Column('size', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('volume_cbm', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    op.drop_table('activity')
    op.drop_table('transport_file')
    op.drop_table('employee')
    op.drop_table('department')
    op.drop_table('contact')
    op.drop_table('client')
    op.drop_table('address')
    # ### end Alembic commands ###
